### ISSUE TITLE
Unstable Stencil

### ISSUE THREAD

**Issue by Sleuthgame** [mriale/PyDPainter#218]
I experienced various crash with **Stencils**.
Hard to replicate. I was just painting for minutes with PyDPainter. I call **Stencil** menu, choose my color, and it crash and exit when I hit **Make** to create the stencil.

Here some recovers. Seems it's the same error. 

[stackdump.txt](https://github.com/user-attachments/files/19335427/stackdump.txt)

dump.

[2025-03-18_182748.zip](https://github.com/user-attachments/files/19335413/2025-03-18_182748.zip)

[stackdump.txt](https://github.com/user-attachments/files/19335441/stackdump.txt)

**Comment by mriale** [comment]
Steps to reproduce:
1. Start PyDPainter
2. Press `j` to swap to spare page
3. Choose Effect/Stencil/Make...
4. Crash

**Comment by mriale** [comment]
@Sleuthgame Looks like this is fixed now. I don't know how that got there! Thanks for finding it!

**Comment by Sleuthgame** [comment]
Oh thanks you ! I use Spare and Stencil a lot, and It wad really frustating. Consider a minor fix update.

**Comment by Sleuthgame** [comment]
It's working again.

Can you check the **toogle** short key ` for **Stencil OFF/ON** ? Seem I have to double hit the key to toogle. Maybe a MS Windows thing, because the ` is a character under the 7 with ALT that need to be followed by a space bar hit to display. I have the same issue in text editor to create this Markdown syntax.
Okay, I get it while writing ! I need to enter the key as a regular character input, (like **ALT-7 Spacebar** or another key) to trigger the **Stencil toogle** into PydPainter. Not a very handy hotkey. If you want to adress this in a AZERTY keyboard, just wait for `è` character. Same key.

**Comment by MetinSeven** [comment]
> Steps to reproduce:
> 
> 1. Start PyDPainter
> 2. Press `j` to swap to spare page
> 3. Choose Effect/Stencil/Make...
> 4. Crash

Just thought to let you know that this crash is still present in the 2.1.0 beta release for macOS.

**Comment by mriale** [comment]
@Sleuthgame 
> Can you check the **toggle** short key for **Stencil OFF/ON** ?

Looks like I added support for the `²` key (which is below the tilde on AZERTY) on 2023-05-22, which is a few releases ago. This makes it the same physical key as on a QWERTY keyboard. I just switched my layout to AZERTY on Linux and Windows 10 and it seemed to work for me. Did it stop working for you? I haven't tried it on Windows 11 because I need to make a Windows 11 VM.

**Comment by Sleuthgame** [comment]
You're right ! I do not remember but I do now. Actually, my `²` key is on the upper left corner of my keyboard, alone. It works.
But the menu is displaying the ` key under 7è which is different for me.
![image](https://cdn.educba.com/academy/wp-content/uploads/2024/01/AZERTY-keyboard-layout.png)

the ~is working the same way, it as to be followed by a space or n for ñ. So the short-key for **Make stencil** is not working as intended either.


I'm on Win10 Pro but I can check on another PC with win11.

**Comment by mriale** [comment]
I think I got the tilde/backtick key working as the `²` key in AZERTY. It worked a little differently in Windows 10 than it did in Linux, but I think it works in both now. I also noticed that I forgot to blank the brush before the requestor popped up so I added that too.

**Comment by Sleuthgame** [comment]
We are good.  `²` is working for on/off, and with SHIFT for **Make** a Stencil.

**Comment by Sleuthgame** [comment]
Nothing to do with Stencil, but you can remove **Print** from **Picture** menu, because it's useless, isn't ?

**Comment by mriale** [comment]
@Sleuthgame
Thanks for reminding me of that! I removed unused **Print** menu option. I think that's been there since I wrote the menu system and everything was a placeholder.
