### ISSUE TITLE
Making the window larger sometimes *decreases* the size of the UI

### ISSUE THREAD

**Issue by jimhigson** [mriale/PyDPainter#253]
See video - here I *increase* the size of the window (in both x and y) which has the effect of *decreasing* the scaling of the app:

https://github.com/user-attachments/assets/f8590da0-b7a1-467c-8c5e-b7cd05a70e6f

This is happening on a 5k screen, under MacOS 26. The screen is a second monitor attached to a Macbook Pro, which is also showing a desktop on the built-in screen.

**Comment by jimhigson** [comment]
I know this problem isn't mathematically complex, but it took quite a lot of trial to get just-so - [here](https://github.com/jimhigson/head-over-heels-online/blob/main/src/store/slices/upscale/calculateUpscale.ts#L43-L74)'s some code I wrote that upscales by first undoing device pixel ratio. The end result is an upscale inside the game engine, and an upscale to apply on top of that using css. The later can be < 0, since it'll render bigger than expected to "undo" HPR and then scale back down.

The video shows it going from original ZX Spectrum resolution (laughably small on a 5k screen) all the way up to being 2160 pixels high. It's tested too on mobile with a DPR of 2x (various Android phones) and 3x (iphone 13 and more), and [the tests](https://github.com/jimhigson/head-over-heels-online/blob/main/src/store/slices/upscale/calculateUpscale.test.ts) cover a fairly good gamut.

I know this isn't exactly the same since you won't have css+in-game scaling to think about, and there's no need to handle device orientation, plus being in a completely different language. But maybe it's translatable with a bit of simplification and could help.

Right now, this makes PyDPainter quite hard to use on larger screens. I can do it but I have to turn my monitor way down to 1080p before launching it. It's worth it for such an awesome product, but it'd be nice not to have to.

https://github.com/user-attachments/assets/9cbbd0de-abd4-47ea-9ae8-872b8c9cad88

**Comment by mriale** [comment]
@jimhigson 
Does it still render small if you use `CTRL`-`+` (or `CTRL`-`=`) to make the window bigger? That's the same as `+/-` in the top-right mini toolbar.

There is some code that limits the magnification to 20x, but I don't think you're hitting that. The `CTRL`-`+` key appears to bypass that check.

**Comment by mriale** [comment]
@jimhigson 

I hope I fixed both issues:
- `CTRL+` and `CTRL-` now makes the window bigger or smaller without the window jumping in size in the wrong direction if it was between 2 sizes.
- The canvas size should scale better now. I took off the limits that were being applied, so it should allow more flexible resizing with multiple screens now.

Please let me know how it works on a 5K screen since I can't test that.

**Comment by jimhigson** [comment]
Testing this, I noticed the MacOS instructions need updating - they omit certain dependencies - [opened a PR here](https://github.com/mriale/PyDPainter/pull/258)

After these changes this seems to be much better although a bug still remains on resizing. Sometimes after resizing it stays at the old size until the mouse enters the window. Video below.

https://github.com/user-attachments/assets/0bf01900-3111-419a-ab71-117265236fbd

**Comment by mriale** [comment]
@jimhigson 

Thanks for the Mac OS installation changes. I merged them in. I'll probably separate the install vs running of PyDPainter though (source the venv though the end).

Glad the sizing is working better now. That makes sense that the PyDPainter interface doesn't redraw until the cursor is inside the window because it's ignoring events so it doesn't redraw. Maybe I can put a half-second timer event on it or something to get it to refresh without the mouse pointer inside.

Again, thanks for your feedback. I wouldn't have been able to fix these things without it.

**Comment by jimhigson** [comment]
I think this can be closed now - the resizing waiting for mouse over is a separate and much smaller issue
